CREATE DATABASE studentdb;
USE studentdb;

CREATE TABLE student (
    id INT(11) NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(40) NOT NULL,
    last_name VARCHAR(40) NOT NULL,
    age INT(11) NOT NULL,
    gender VARCHAR(20) NOT NULL,
    email VARCHAR(40) NOT NULL,
    faculty VARCHAR(40) NOT NULL,
    PRIMARY KEY (id)
);

CREATE USER 'USERNAME'@'127.0.0.1' IDENTIFIED BY 'PASSWORD';
GRANT ALL PRIVILEGES ON studentdb.* TO 'USERNAME'@'127.0.0.1';
FLUSH PRIVILEGES;
EXIT;
